version: "3.7"
services:
  postgres:
    image: postgres:10.5
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=transcendence_backend_db
    ports:
      - "5432:5432"
    volumes:
      - pg_db:/var/pg_db
    restart: always

  backend:
    build:
      context: "./backend"
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - avatars:/usr/src/app/avatars

  frontend:
    build:
      context: "./front"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - backend

volumes:
  avatars:
  pg_db:
